[package]
name = "p2p-play-frontend"
version = "0.10.6"
edition = "2024"
authors = ["P2P-Play Contributors"]
description = "A peer-to-peer story sharing application with Terminal User Interface"

[dependencies]
p2p-network = { path = "../p2p-network" }
tokio = { version = "1.43", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "fs"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.5"
log = "0.4"
env_logger = "0.10"
futures = "0.3.15"
bytes = "1.0"
rusqlite = { version = "0.29", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.22"
ratatui = "0.27"
crossterm = "0.27"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8"
uuid = { version = "1.0", features = ["v4"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }