[tool.tarpaulin.default]
# Exclude the main function from coverage as it's hard to test
exclude-files = []

# Exclude main function and UI initialization from coverage
exclude = [
    "src/main.rs:main",
    "src/ui.rs:new",
    "src/ui.rs:cleanup",
]

# Coverage threshold - we want to improve from ~35%
fail-under = 40.0

# Output formats
out = ["Html", "Xml"]
output-dir = "coverage/"