[tool.tarpaulin.default]
# Exclude the main function from coverage as it's hard to test
exclude-files = [
    "src/main.rs",
]

# Exclude main function and UI initialization from coverage
exclude = [
    "src/ui.rs:new",
    "src/ui.rs:cleanup", 
    "src/ui.rs:draw",
    "src/ui.rs:should_process_key_event",
]

# Coverage threshold - we want to improve from ~35%
fail-under = 40.0

# Output formats
out = ["Html", "Xml"]
output-dir = "coverage/"
