[tool.tarpaulin.default]
# Exclude the main function from coverage as it's hard to test
exclude-files = []

# Exclude lines that cannot realistically be tested
exclude = [
    # Main event loop and initialization code that's hard to test
    "src/main.rs:27-325",
    # Process exit calls that would terminate the test runner
    "src/main.rs:47-48",
    "src/main.rs:54-55",
    "src/event_handlers.rs:116",
    # Error handling for UI failures that would break tests
    "src/main.rs:142-144",
    "src/main.rs:147-149",
    "src/main.rs:322-324",
    # Network initialization that requires actual network setup
    "src/main.rs:73",
    "src/main.rs:131-137",
]

# Coverage threshold - we want to improve from ~35%
fail-under = 40.0

# Output formats
out = ["Html", "Xml"]
output-dir = "coverage/"