# Exclude files that are primarily terminal I/O and hard to test
exclude-files = [
    "src/main.rs",
    "src/ui.rs",
]

# Coverage threshold - we want to improve from ~35%
fail-under = 40.0

# Output formats
out = ["Html", "Xml"]
output-dir = "coverage/"
