name: P2P Core CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'p2p-core/**'
      - '.github/workflows/p2p-core-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'p2p-core/**'
      - '.github/workflows/p2p-core-ci.yml'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-A warnings"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check code formatting
      run: |
        cd p2p-core
        cargo fmt --all -- --check
    
    - name: Run clippy
      run: |
        cd p2p-core  
        cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Build
      run: |
        cd p2p-core
        cargo build --verbose
    
    - name: Run tests
      run: |
        cd p2p-core
        ./scripts/test_runner.sh

  coverage:
    name: Code Coverage  
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    
    - name: Generate coverage report
      run: |
        cd p2p-core
        ./scripts/coverage.sh
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./p2p-core/coverage/cobertura.xml
        directory: ./p2p-core/coverage/
        flags: p2p-core
        name: p2p-core-coverage
        fail_ci_if_error: false

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust  
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run security audit
      run: |
        cd p2p-core
        cargo audit

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    
    - name: Cache cargo dependencies  
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build documentation
      run: |
        cd p2p-core
        cargo doc --no-deps --all-features
      env:
        RUSTDOCFLAGS: "-D warnings"