[package]
name = "p2p-network"
version = "0.1.0"
edition = "2021"
authors = ["P2P-Play Contributors"]
description = "A reusable peer-to-peer networking library built on libp2p"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/p2p-network"
keywords = ["p2p", "networking", "libp2p", "distributed", "peer-to-peer"]
categories = ["network-programming", "cryptography"]

[dependencies]
libp2p = { version = "0.56.0", features = [  "tcp", "tokio", "floodsub", "macros", "identify", "mdns", "yamux", "noise", "ping", "request-response", "cbor", "kad", "memory-connection-limits", "dns", "rsa", "relay"] }
tokio = { version = "1.43", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "fs"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.5"
log = "0.4"
futures = "0.3.15"
bytes = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
zeroize = "1.8"
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8"
uuid = { version = "1.0", features = ["v4"] }
tokio-test = "0.4"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }