name: Development Build

on:
  workflow_dispatch:
  push:
    branches: [ "bug/windows-fix" ]

jobs:
  windows-build:
    name: Build Windows Binary
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build binary
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4
      with:
        name: p2p-play-windows-dev
        path: target/x86_64-pc-windows-msvc/release/p2p-play.exe
        retention-days: 3
